<?php

namespace AppBundle\Repository;

/**
 * SubFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubFileRepository extends \Doctrine\ORM\EntityRepository
{
}
