<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNumberOfDownloads() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT SUM(u.downloads) FROM AppBundle:User u'
            )
            ->getResult();
    }
    public function getNumberOfUsers() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(u.id) FROM AppBundle:User u'
            )
            ->getResult();
    }
}
